name: 'Pull Request Target Branch Action'
description: 'A action to check that a PR''s target branch is correct, commenting and/or changing it if required'

inputs:
  target:
    description: 'The target branch'
    required: true
  exclude:
    description: 'A list (space separated string) of base branches which are allowed to PR the given target (cannot be used with include)'
    required: false
  include:
    description: 'A list (space separated string) of base branches which are not allowed to PR the given target (cannot be used with exclude)'
    required: false

  change-to:
    description: 'The branch the PR''s target should be changed to if the target is incorrect'
    required: false
  comment:
    description: 'The comment that will be posted when the target branch is incorrect'
    required: false

  already-exists-action:
    description: 'The action to take if a pr with the same head & base already exists'
    required: false
    default: 'error'
  already-exists-comment:
    description: 'The comment to post if a pr with the same head & base already exists'
    required: false
  already-exists-other-comment:
    description: 'The comment to post on the other pr if already-exists-action closes the other pr'
    required: false

outputs:
  wrong-target:
    description: 'Boolean output indicating if the target branch was incorrect'
  comment-posted:
    description: 'The comment that was posted, if any'
  new-target:
    description: 'The new target, if the target was changed'
  pr-already-exists:
    description: 'If a pr with the same head & base already exists'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'
  color: 'orange'
